# Generated by Django 3.2.7 on 2021-09-27 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiSubApp', '0002_department_instructor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
