# Generated by Django 3.2.7 on 2021-09-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiSubApp', '0004_remove_instructor_belongs_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_body',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='task_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
