# Generated by Django 3.2.7 on 2021-09-27 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiSubApp', '0005_auto_20210927_1005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
